### PR TITLE
Update Readme.txt : add fastlz 

### PR DESCRIPTION
**Pull request by bizulk**
I used this project a month ago for real time compression on cortex-M4 (160Mhz, 192 ko RAM). The ratio beetween speed / size is good to me.
This project was simplest to embbed.
The community on google groups is reactive.

### CODE REVIEW

**Comment by kozross** [comment]
Having (finally!) had a look, this seems a bit suspect. Firstly, the repository is archived. Does this mean it's no longer maintained? If there's nowhere to report issues, I'm not sure it's a good idea to include it here. If there _is_ a 'live' copy, we should link to it instead.

**Comment by bizulk** [comment]
I may ask to the autor if he can suggest some maintainer.

**Comment by bizulk** [comment]
awaiting return from google [group](https://groups.google.com/forum/#!forum/fastlz):

**Comment by bizulk** [comment]
I have no return from google group so far.
This project has been forked many times I may ask to one of them that is open and the most recently updated to be referenced.
It would be nice to acheive adding fastLZ, as this compressor is really easy to embbed and use for realtime compression on micro-Embbeded target. The codec is package in python, and the php [memcached ](https://github.com/php-memcached-dev/php-memcached)plugin.
I tried LZ4 but is requires tweaking the sources to use external memory for the hash table.

**Comment by kozross** [comment]
@bizulk Would you be interested in forking and maintaining? I can't do it (I have enough to handle as it is), and I feel _very_ uncomfortable adding something where I have no bug reporting avenue or even a clear maintainer.

**Comment by bizulk** [comment]
I may be interested, if adding test case code and doc, merging pull request could be sufficient to you. 
Actually I'm not competent to LZ77, but I feel that the code has not been changing a lot because it is simple and stable and there is nothing in particular to change to the core of the project.

Plz wait a week or a bit more, I would ask to someone before, and try to have a clean and updated repo to present.

**Comment by kozross** [comment]
@bizulk Happy 2020! Any progress on this?

**Comment by bizulk** [comment]
Hello !

The author has sent a mail in reply : 

> The current implementation of FastLZ is considered "stable", hence why it doesn't see/need much improvements.
> 
> For a good measure, I've updated the README to mention a couple of things:
> 
> * where it is being used: from games (as Death Stranding) to various open-source projects (Godot Engine, Facebook HHVM, Apache Traffic Server, Calligra Office, OSv, Netty, etc).
> * the CI system verifies the build and runs the tests on 23 different combinations of architectures (amd64,i686, arm64, armhf, mips), operating systems (Linux, macOS, Windows), compilers (Clang, GCC, VS2017/2019, Tiny CC).
> * available language bindings to work with it from Rust, Lua, Python, Ruby, etc
> 
> If there are more concerns, please let me know. Thank you very much!

If that answer is not sastisfying, I will try to fork the repo and add some stuff to it like a embbeded project for demonstration.
When I don't knwo sincerly.

We may close the issue, I'll add one when something new arrives.

**Comment by kozross** [comment]
@bizulk So... what's happening here?

**Comment by oz123** [comment]
Merged in  b62b6ff

**Pull request closed without merging**
